workflow: Use ghc 9.0
Deprecation erros with 9.2:

```
src/Nixon/Project.hs:94:30: error: [-Wdeprecations, -Werror=deprecations]
Error:     In the use of ‘fromText’
    (imported from Turtle, but defined in turtle-1.6.1-3100060682019b4f9d6b423a178555349ed83e17f8560130491edee3fc343d4a:Turtle.Internal):
    Deprecated: "Use Data.Text.unpack instead"
   |
94 |   fromString = ProjectPath . fromText . T.pack
   |                              ^^^^^^^^

src/Nixon/Project.hs:179:41: error: [-Wdeprecations, -Werror=deprecations]
Error:     In the use of ‘encodeString’
    (imported from Turtle, but defined in turtle-1.6.1-3100060682019b4f9d6b423a178555349ed83e17f8560130491edee3fc343d4a:Turtle.Internal):
    Deprecated: "Use id instead"
    |
179 |   expanded <- liftIO $ wordexp nosubst (encodeString path')
    |                                         ^^^^^^^^^^^^
cabal: Failed to build nixon-0.1.0.0 (which is required by test:nixon-test
from nixon-0.1.0.0 and exe:nixon from nixon-0.1.0.0).

Error: Process completed with exit code 1.
```